/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as MealMealIdRouteImport } from './routes/meal.$mealId'
import { Route as MoodMoodIdRouteImport } from './routes/mood.$moodId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MealMealIdRoute = MealMealIdRouteImport.update({
  id: '/meal/$mealId',
  path: '/meal/$mealId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodMoodIdRoute = MoodMoodIdRouteImport.update({
  id: '/mood/$moodId',
  path: '/mood/$moodId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/our-story': typeof OurStoryRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/meal/$mealId': typeof MealMealIdRoute
  '/mood/$moodId': typeof MoodMoodIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/our-story': typeof OurStoryRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/meal/$mealId': typeof MealMealIdRoute
  '/mood/$moodId': typeof MoodMoodIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/our-story': typeof OurStoryRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/meal/$mealId': typeof MealMealIdRoute
  '/mood/$moodId': typeof MoodMoodIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/how-it-works'
    | '/journal'
    | '/login'
    | '/our-story'
    | '/privacy'
    | '/profile'
    | '/saved'
    | '/signup'
    | '/terms'
    | '/meal/$mealId'
    | '/mood/$moodId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/how-it-works'
    | '/journal'
    | '/login'
    | '/our-story'
    | '/privacy'
    | '/profile'
    | '/saved'
    | '/signup'
    | '/terms'
    | '/meal/$mealId'
    | '/mood/$moodId'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/how-it-works'
    | '/journal'
    | '/login'
    | '/our-story'
    | '/privacy'
    | '/profile'
    | '/saved'
    | '/signup'
    | '/terms'
    | '/meal/$mealId'
    | '/mood/$moodId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  OurStoryRoute: typeof OurStoryRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  MealMealIdRoute: typeof MealMealIdRoute
  MoodMoodIdRoute: typeof MoodMoodIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal/$mealId': {
      id: '/meal/$mealId'
      path: '/meal/$mealId'
      fullPath: '/meal/$mealId'
      preLoaderRoute: typeof MealMealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/$moodId': {
      id: '/mood/$moodId'
      path: '/mood/$moodId'
      fullPath: '/mood/$moodId'
      preLoaderRoute: typeof MoodMoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  HowItWorksRoute: HowItWorksRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  OurStoryRoute: OurStoryRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  MealMealIdRoute: MealMealIdRoute,
  MoodMoodIdRoute: MoodMoodIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
